name = "postgres_wasm"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[dev]
local_protocol = "http"
upstream_protocol = "http"

[build]
command = "cargo install -q worker-build && worker-build --release"
